server:
  port: 7001

spring:
  application:
    name: microservicecloud-config-eureka-client

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    hostname: eureka7001.com
